#!/usr/bin/env php
<?php
if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}
$app = new Symfony\Component\Console\Application('Storm for Cloud9', '1.0');
$app->add(new Storm\Conjure);
$app->add(new Storm\Clear);
$app->add(new Storm\Up);
$app->add(new Storm\Down);
$app->run();
